// ============================================================
//  script.js  ―  共通データ & ユーティリティ
//  全ページから読み込む。window.MEALS / window.Utils を公開。
// ============================================================

window.MEALS = [
  // ===== 和食 =====
  { name:"肉じゃが", emoji:"🥔", category:"和食", desc:"ほっこり定番の煮物", servings:4,
    ingredients:[{name:"牛肉（薄切り）",amount:200,unit:"g"},{name:"じゃがいも",amount:3,unit:"個"},{name:"玉ねぎ",amount:1,unit:"個"},{name:"にんじん",amount:1,unit:"本"},{name:"しらたき",amount:100,unit:"g"},{name:"醤油",amount:3,unit:"大さじ"},{name:"みりん",amount:3,unit:"大さじ"},{name:"砂糖",amount:1.5,unit:"大さじ"},{name:"だし汁",amount:200,unit:"ml"}],
    steps:["じゃがいも・にんじんは乱切り、玉ねぎはくし切り","牛肉を炒めて色が変わったら野菜を加える","だし汁・調味料を入れ中火で20分煮る","じゃがいもが柔らかくなったら完成"]},
  { name:"から揚げ", emoji:"🍗", category:"和食", desc:"みんな大好き揚げたて", servings:4,
    ingredients:[{name:"鶏もも肉",amount:500,unit:"g"},{name:"醤油",amount:2,unit:"大さじ"},{name:"酒",amount:1,unit:"大さじ"},{name:"おろし生姜",amount:1,unit:"小さじ"},{name:"おろしにんにく",amount:1,unit:"小さじ"},{name:"片栗粉",amount:4,unit:"大さじ"},{name:"揚げ油",amount:1,unit:"適量"}],
    steps:["鶏肉を一口大に切り、醤油・酒・生姜・にんにくで15分漬ける","片栗粉をまぶす","170℃の油で4分揚げ、取り出して2分休ませる","180℃で1分揚げてカリッと仕上げる"]},
  { name:"鮭の塩焼き", emoji:"🐟", category:"和食", desc:"シンプルで体に優しい", servings:2,
    ingredients:[{name:"生鮭",amount:2,unit:"切れ"},{name:"塩",amount:0.5,unit:"小さじ"},{name:"大根おろし",amount:1,unit:"適量"},{name:"レモン",amount:0.5,unit:"個"}],
    steps:["鮭に塩を振り15分おく","水分をペーパーで拭き取る","グリルで中火8分焼く","大根おろし・レモンを添えて完成"]},
  { name:"豚の生姜焼き", emoji:"🥩", category:"和食", desc:"甘辛タレでご飯に合う", servings:2,
    ingredients:[{name:"豚ロース薄切り",amount:200,unit:"g"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"醤油",amount:2,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"},{name:"酒",amount:1,unit:"大さじ"},{name:"おろし生姜",amount:1,unit:"大さじ"}],
    steps:["調味料を混ぜてたれを作る","豚肉をたれに5分漬ける","フライパンで玉ねぎを炒め豚肉を加える","たれを絡めながら炒めて完成"]},
  { name:"鶏の照り焼き", emoji:"🍖", category:"和食", desc:"照りツヤでご飯が止まらない", servings:2,
    ingredients:[{name:"鶏もも肉",amount:300,unit:"g"},{name:"醤油",amount:2,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"小さじ"},{name:"サラダ油",amount:1,unit:"大さじ"}],
    steps:["鶏肉の皮目をフォークで刺す","皮目から中火で焼く","裏返し蓋をして5分蒸し焼き","たれを絡めて照りが出るまで煮詰める"]},
  { name:"親子丼", emoji:"🥚", category:"和食", desc:"ふわとろ卵と鶏肉", servings:2,
    ingredients:[{name:"鶏もも肉",amount:200,unit:"g"},{name:"卵",amount:4,unit:"個"},{name:"玉ねぎ",amount:1,unit:"個"},{name:"だし汁",amount:150,unit:"ml"},{name:"醤油",amount:2,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"},{name:"ご飯",amount:2,unit:"膳"}],
    steps:["鶏肉を一口大、玉ねぎを薄切りに","だし汁・醤油・みりんで煮る","溶き卵を回し入れ半熟で止める","ご飯の上に乗せて完成"]},
  { name:"かつ丼", emoji:"🍱", category:"和食", desc:"ジューシーカツに卵とじ", servings:2,
    ingredients:[{name:"豚ロースカツ",amount:2,unit:"枚"},{name:"卵",amount:4,unit:"個"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"だし汁",amount:150,unit:"ml"},{name:"醤油",amount:2,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"}],
    steps:["カツを4cm幅に切る","だし汁・醤油・みりんで玉ねぎを煮る","カツを加え卵を回し入れ半熟に","ご飯の上にのせて完成"]},
  { name:"さばの味噌煮", emoji:"🐡", category:"和食", desc:"濃厚味噌ダレが絶品", servings:2,
    ingredients:[{name:"さば",amount:2,unit:"切れ"},{name:"味噌",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"みりん",amount:1,unit:"大さじ"},{name:"酒",amount:2,unit:"大さじ"},{name:"水",amount:100,unit:"ml"},{name:"生姜",amount:1,unit:"かけ"}],
    steps:["さばに熱湯をかけ臭みを取る","水・酒・砂糖・みりんを煮立てる","さばを入れ落とし蓋で10分煮る","味噌を溶かし煮詰めて完成"]},
  { name:"豚汁", emoji:"🍲", category:"和食", desc:"野菜たっぷり温まる", servings:4,
    ingredients:[{name:"豚バラ肉",amount:150,unit:"g"},{name:"大根",amount:0.25,unit:"本"},{name:"にんじん",amount:1,unit:"本"},{name:"じゃがいも",amount:2,unit:"個"},{name:"ごぼう",amount:0.5,unit:"本"},{name:"味噌",amount:4,unit:"大さじ"},{name:"だし汁",amount:800,unit:"ml"}],
    steps:["野菜を切り豚肉は3cm幅に","ごま油で豚肉を炒め野菜を加える","だし汁を入れ柔らかくなるまで煮る","火を止めて味噌を溶かし入れる"]},
  { name:"天ぷら定食", emoji:"🍤", category:"和食", desc:"サクサク揚げたて", servings:2,
    ingredients:[{name:"えび",amount:8,unit:"尾"},{name:"さつまいも",amount:1,unit:"個"},{name:"かぼちゃ",amount:100,unit:"g"},{name:"薄力粉",amount:100,unit:"g"},{name:"卵",amount:1,unit:"個"},{name:"冷水",amount:150,unit:"ml"},{name:"揚げ油",amount:1,unit:"適量"}],
    steps:["衣は冷水・卵・薄力粉を軽く混ぜる","野菜は薄切り、えびは背ワタを取る","170℃で野菜2分・えび2分揚げる","天つゆと大根おろしを添えて完成"]},
  { name:"すき焼き", emoji:"🫕", category:"和食", desc:"甘辛割り下で特別な夜", servings:4,
    ingredients:[{name:"牛肉（すき焼き用）",amount:400,unit:"g"},{name:"豆腐",amount:1,unit:"丁"},{name:"白菜",amount:0.25,unit:"個"},{name:"ねぎ",amount:2,unit:"本"},{name:"しらたき",amount:1,unit:"袋"},{name:"醤油",amount:4,unit:"大さじ"},{name:"みりん",amount:4,unit:"大さじ"},{name:"砂糖",amount:2,unit:"大さじ"}],
    steps:["割り下を合わせる","牛脂を溶かし牛肉を焼く","割り下と野菜・豆腐を加える","生卵につけて召し上がれ"]},
  { name:"ぶり大根", emoji:"🐠", category:"和食", desc:"脂乗りブリと大根の煮物", servings:2,
    ingredients:[{name:"ぶり",amount:2,unit:"切れ"},{name:"大根",amount:0.5,unit:"本"},{name:"醤油",amount:3,unit:"大さじ"},{name:"みりん",amount:3,unit:"大さじ"},{name:"酒",amount:3,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"水",amount:200,unit:"ml"}],
    steps:["大根を下茹でする","ぶりに塩を振り熱湯をかける","調味料と大根を10分煮る","ぶりを加えて落し蓋で15分煮る"]},
  { name:"鶏そぼろ丼", emoji:"🍚", category:"和食", desc:"三色そぼろが映える", servings:2,
    ingredients:[{name:"鶏ひき肉",amount:200,unit:"g"},{name:"卵",amount:2,unit:"個"},{name:"醤油",amount:2,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"さやいんげん",amount:8,unit:"本"},{name:"ご飯",amount:2,unit:"膳"}],
    steps:["鶏ひき肉を炒り煮にする","卵は炒り卵を作る","いんげんは塩茹でして斜め切り","ご飯の上に三色に並べて完成"]},
  { name:"牛丼", emoji:"🐄", category:"和食", desc:"甘辛牛肉がご飯に絡む", servings:2,
    ingredients:[{name:"牛肉薄切り",amount:200,unit:"g"},{name:"玉ねぎ",amount:1,unit:"個"},{name:"醤油",amount:2,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"だし汁",amount:100,unit:"ml"},{name:"ご飯",amount:2,unit:"膳"}],
    steps:["玉ねぎを薄切りにする","だし汁・調味料で玉ねぎを煮る","牛肉を加えてほぐしながら煮る","ご飯にのせて完成"]},
  { name:"筑前煮", emoji:"🥕", category:"和食", desc:"根菜たっぷり煮しめ", servings:4,
    ingredients:[{name:"鶏もも肉",amount:200,unit:"g"},{name:"ごぼう",amount:1,unit:"本"},{name:"にんじん",amount:1,unit:"本"},{name:"れんこん",amount:100,unit:"g"},{name:"こんにゃく",amount:0.5,unit:"枚"},{name:"醤油",amount:3,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"}],
    steps:["食材をすべて乱切りにする","ごま油で鶏肉を炒め野菜を加える","だし汁と調味料を煮立てる","落し蓋して20分煮込んで完成"]},
  { name:"おでん", emoji:"🫙", category:"和食", desc:"冬に恋しい出汁の味", servings:4,
    ingredients:[{name:"大根",amount:0.5,unit:"本"},{name:"卵",amount:4,unit:"個"},{name:"こんにゃく",amount:1,unit:"枚"},{name:"ちくわ",amount:4,unit:"本"},{name:"はんぺん",amount:1,unit:"枚"},{name:"だし汁",amount:1200,unit:"ml"},{name:"醤油",amount:3,unit:"大さじ"},{name:"みりん",amount:2,unit:"大さじ"}],
    steps:["大根を下茹でする","卵はゆで卵にする","だし汁・醤油・みりんで出汁を作る","具材を入れて弱火で30分以上煮込む"]},
  { name:"豆腐ステーキ", emoji:"🧆", category:"和食", desc:"ヘルシーでボリューム満点", servings:2,
    ingredients:[{name:"木綿豆腐",amount:1,unit:"丁"},{name:"醤油",amount:2,unit:"大さじ"},{name:"みりん",amount:1,unit:"大さじ"},{name:"砂糖",amount:0.5,unit:"小さじ"},{name:"片栗粉",amount:2,unit:"大さじ"},{name:"ごま油",amount:1,unit:"大さじ"}],
    steps:["豆腐を水切りして2cm厚さに切る","片栗粉をまぶす","ごま油で両面きつね色に焼く","たれをかけて完成"]},
  { name:"鮭のちゃんちゃん焼き", emoji:"🫕", category:"和食", desc:"北海道の郷土料理", servings:2,
    ingredients:[{name:"生鮭",amount:2,unit:"切れ"},{name:"キャベツ",amount:0.25,unit:"個"},{name:"もやし",amount:1,unit:"袋"},{name:"味噌",amount:2,unit:"大さじ"},{name:"みりん",amount:1,unit:"大さじ"},{name:"酒",amount:1,unit:"大さじ"},{name:"バター",amount:20,unit:"g"}],
    steps:["野菜を切る","鍋に野菜を敷き鮭を乗せる","合わせ味噌とバターを乗せて蓋をして蒸す","全体を混ぜて完成"]},
  { name:"冷やし中華", emoji:"🍝", category:"和食", desc:"夏にぴったりさっぱり麺", servings:2,
    ingredients:[{name:"中華麺",amount:2,unit:"玉"},{name:"ハム",amount:4,unit:"枚"},{name:"きゅうり",amount:1,unit:"本"},{name:"卵",amount:2,unit:"個"},{name:"醤油",amount:2,unit:"大さじ"},{name:"酢",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"ごま油",amount:1,unit:"大さじ"}],
    steps:["麺を茹でて冷水で締める","卵は薄焼き卵にして細切り","きゅうり・ハムも細切りに","たれを作り具材を盛り付けて完成"]},
  // ===== 洋食 =====
  { name:"ハンバーグ", emoji:"🍔", category:"洋食", desc:"子どもも大人も大喜び", servings:4,
    ingredients:[{name:"牛豚合いびき肉",amount:400,unit:"g"},{name:"玉ねぎ",amount:1,unit:"個"},{name:"パン粉",amount:4,unit:"大さじ"},{name:"牛乳",amount:3,unit:"大さじ"},{name:"卵",amount:1,unit:"個"},{name:"塩こしょう",amount:1,unit:"適量"},{name:"ケチャップ",amount:2,unit:"大さじ"},{name:"ウスターソース",amount:2,unit:"大さじ"}],
    steps:["玉ねぎをみじん切りにして炒め冷ます","ひき肉・玉ねぎ・パン粉・牛乳・卵で混ぜる","楕円形に成形","両面焼きソースをかけて完成"]},
  { name:"チキンカレー", emoji:"🍛", category:"洋食", desc:"スパイス香る本格派", servings:4,
    ingredients:[{name:"鶏もも肉",amount:400,unit:"g"},{name:"玉ねぎ",amount:2,unit:"個"},{name:"にんじん",amount:1,unit:"本"},{name:"じゃがいも",amount:2,unit:"個"},{name:"カレールー",amount:100,unit:"g"},{name:"水",amount:700,unit:"ml"}],
    steps:["玉ねぎを飴色になるまで炒める","鶏肉・野菜を加えて炒める","水を入れ20分煮込む","ルーを溶かし入れ5分煮て完成"]},
  { name:"ビーフシチュー", emoji:"🥘", category:"洋食", desc:"とろとろ牛肉が溶ける", servings:4,
    ingredients:[{name:"牛すね肉",amount:500,unit:"g"},{name:"玉ねぎ",amount:2,unit:"個"},{name:"にんじん",amount:1,unit:"本"},{name:"じゃがいも",amount:2,unit:"個"},{name:"赤ワイン",amount:200,unit:"ml"},{name:"デミグラスソース",amount:1,unit:"缶"},{name:"トマト缶",amount:0.5,unit:"缶"},{name:"バター",amount:20,unit:"g"}],
    steps:["牛肉を一口大に切り塩こしょう","バターで玉ねぎと牛肉を焼く","赤ワイン・トマト・デミグラスを加える","弱火で2時間煮込む"]},
  { name:"オムライス", emoji:"🍳", category:"洋食", desc:"ふわとろ卵で包んで", servings:2,
    ingredients:[{name:"ご飯",amount:300,unit:"g"},{name:"鶏もも肉",amount:100,unit:"g"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"卵",amount:4,unit:"個"},{name:"ケチャップ",amount:3,unit:"大さじ"},{name:"バター",amount:20,unit:"g"}],
    steps:["鶏肉・玉ねぎを炒めご飯・ケチャップを加える","チキンライスを皿に盛る","バターでふわとろ卵を作る","チキンライスにのせてケチャップをかける"]},
  { name:"グラタン", emoji:"🧀", category:"洋食", desc:"とろけるチーズが最高", servings:2,
    ingredients:[{name:"鶏もも肉",amount:150,unit:"g"},{name:"マカロニ",amount:80,unit:"g"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"牛乳",amount:300,unit:"ml"},{name:"薄力粉",amount:2,unit:"大さじ"},{name:"バター",amount:20,unit:"g"},{name:"ピザ用チーズ",amount:60,unit:"g"}],
    steps:["マカロニを茹でる","バターで野菜・鶏肉を炒め薄力粉を加える","牛乳を少しずつ加えホワイトソースを作る","耐熱皿に入れチーズをのせ200℃で20分焼く"]},
  { name:"ポークソテー", emoji:"🥩", category:"洋食", desc:"マスタードソースで大人味", servings:2,
    ingredients:[{name:"豚ロース厚切り",amount:2,unit:"枚"},{name:"粒マスタード",amount:1,unit:"大さじ"},{name:"醤油",amount:1,unit:"大さじ"},{name:"みりん",amount:1,unit:"大さじ"},{name:"バター",amount:10,unit:"g"}],
    steps:["豚肉の筋を切り塩こしょう","両面に焼き色をつける","アルミホイルで5分休ませる","ソース材料を炒め豚肉にかけて完成"]},
  { name:"クリームシチュー", emoji:"🍲", category:"洋食", desc:"まろやかクリームに野菜たっぷり", servings:4,
    ingredients:[{name:"鶏もも肉",amount:300,unit:"g"},{name:"玉ねぎ",amount:1,unit:"個"},{name:"にんじん",amount:1,unit:"本"},{name:"じゃがいも",amount:2,unit:"個"},{name:"シチューのルー",amount:90,unit:"g"},{name:"牛乳",amount:200,unit:"ml"},{name:"水",amount:600,unit:"ml"}],
    steps:["野菜・鶏肉を一口大に切る","バターで炒め水を加えて15分煮る","ルーを溶かし入れる","牛乳を加えて弱火で5分煮て完成"]},
  { name:"ロールキャベツ", emoji:"🥬", category:"洋食", desc:"じっくり煮込んだ洋食の定番", servings:4,
    ingredients:[{name:"牛豚合いびき肉",amount:300,unit:"g"},{name:"キャベツ",amount:8,unit:"枚"},{name:"玉ねぎ",amount:1,unit:"個"},{name:"卵",amount:1,unit:"個"},{name:"コンソメ",amount:2,unit:"個"},{name:"トマト缶",amount:1,unit:"缶"}],
    steps:["キャベツを茹でてしんなりさせる","肉だねを作る","キャベツで包む","コンソメ・トマト缶で30分煮込む"]},
  { name:"カルボナーラ", emoji:"🍝", category:"洋食", desc:"濃厚卵とチーズのパスタ", servings:2,
    ingredients:[{name:"スパゲッティ",amount:180,unit:"g"},{name:"ベーコン",amount:80,unit:"g"},{name:"卵",amount:2,unit:"個"},{name:"卵黄",amount:2,unit:"個"},{name:"粉チーズ",amount:4,unit:"大さじ"},{name:"黒こしょう",amount:1,unit:"適量"}],
    steps:["パスタを茹でる","ベーコンをカリカリに炒める","卵・卵黄・粉チーズ・黒こしょうを混ぜる","火を止めたフライパンでパスタと和えて完成"]},
  { name:"コロッケ", emoji:"🥔", category:"洋食", desc:"サクサクじゃがいもコロッケ", servings:4,
    ingredients:[{name:"じゃがいも",amount:4,unit:"個"},{name:"牛豚合いびき肉",amount:150,unit:"g"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"薄力粉",amount:1,unit:"適量"},{name:"卵",amount:2,unit:"個"},{name:"パン粉",amount:1,unit:"適量"},{name:"揚げ油",amount:1,unit:"適量"}],
    steps:["じゃがいもを茹でてつぶす","ひき肉・玉ねぎを炒め塩こしょうで味付け","じゃがいもと混ぜ形を整える","薄力粉・卵・パン粉をつけ180℃で揚げる"]},
  { name:"ペペロンチーノ", emoji:"🌶️", category:"洋食", desc:"シンプルにんにく唐辛子", servings:2,
    ingredients:[{name:"スパゲッティ",amount:180,unit:"g"},{name:"にんにく",amount:4,unit:"かけ"},{name:"鷹の爪",amount:2,unit:"本"},{name:"オリーブオイル",amount:4,unit:"大さじ"},{name:"塩",amount:1,unit:"適量"},{name:"パセリ",amount:1,unit:"適量"}],
    steps:["パスタを茹でる（茹で汁を取っておく）","にんにく・鷹の爪をオリーブオイルで炒める","茹で汁を加えて乳化させる","パスタを絡めてパセリをかけて完成"]},
  { name:"タコライス", emoji:"🌮", category:"洋食", desc:"沖縄発のアレンジご飯", servings:2,
    ingredients:[{name:"牛豚合いびき肉",amount:200,unit:"g"},{name:"レタス",amount:4,unit:"枚"},{name:"トマト",amount:1,unit:"個"},{name:"チーズ",amount:40,unit:"g"},{name:"ケチャップ",amount:2,unit:"大さじ"},{name:"チリパウダー",amount:1,unit:"小さじ"},{name:"ご飯",amount:2,unit:"膳"}],
    steps:["ひき肉をケチャップ・チリパウダーで炒める","レタスは千切り、トマトはざく切り","ご飯の上にレタスを敷く","ひき肉・トマト・チーズをのせて完成"]},
  { name:"キーマカレー", emoji:"🍛", category:"洋食", desc:"スパイシーひき肉カレー", servings:4,
    ingredients:[{name:"鶏ひき肉",amount:400,unit:"g"},{name:"玉ねぎ",amount:2,unit:"個"},{name:"トマト缶",amount:1,unit:"缶"},{name:"カレー粉",amount:2,unit:"大さじ"},{name:"にんにく",amount:2,unit:"かけ"},{name:"生姜",amount:1,unit:"かけ"},{name:"ご飯",amount:4,unit:"膳"}],
    steps:["玉ねぎを飴色に炒める","にんにく・生姜・カレー粉を加える","ひき肉・トマト缶を加えて煮込む","水分を飛ばしてご飯に盛り付ける"]},
  { name:"サーモンのムニエル", emoji:"🐟", category:"洋食", desc:"バターソースが芳醇", servings:2,
    ingredients:[{name:"サーモン",amount:2,unit:"切れ"},{name:"薄力粉",amount:2,unit:"大さじ"},{name:"バター",amount:30,unit:"g"},{name:"レモン",amount:0.5,unit:"個"},{name:"パセリ",amount:1,unit:"適量"}],
    steps:["サーモンに塩こしょうをふり薄力粉をまぶす","バターでゆっくり両面を焼く","残ったバターにレモン汁を加えソースを作る","パセリを散らして完成"]},
  { name:"ナポリタン", emoji:"🍝", category:"洋食", desc:"ケチャップ炒めの懐かし麺", servings:2,
    ingredients:[{name:"スパゲッティ",amount:180,unit:"g"},{name:"ウインナー",amount:4,unit:"本"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"ピーマン",amount:2,unit:"個"},{name:"ケチャップ",amount:4,unit:"大さじ"},{name:"バター",amount:10,unit:"g"}],
    steps:["パスタを茹でる","野菜・ウインナーを炒める","ケチャップを加えて炒める","パスタを加えて絡めて完成"]},
  { name:"チキンドリア", emoji:"🧀", category:"洋食", desc:"ホワイトソースがとろける", servings:2,
    ingredients:[{name:"鶏もも肉",amount:150,unit:"g"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"ご飯",amount:300,unit:"g"},{name:"牛乳",amount:250,unit:"ml"},{name:"薄力粉",amount:2,unit:"大さじ"},{name:"バター",amount:20,unit:"g"},{name:"ピザ用チーズ",amount:60,unit:"g"}],
    steps:["バターで鶏肉・玉ねぎを炒める","薄力粉と牛乳でホワイトソースを作る","耐熱皿にご飯・ソースの順に入れる","チーズをかけて220℃で15分焼く"]},
  // ===== 中華 =====
  { name:"麻婆豆腐", emoji:"🌶️", category:"中華", desc:"ピリ辛でご飯が進む", servings:4,
    ingredients:[{name:"豆腐",amount:1,unit:"丁"},{name:"豚ひき肉",amount:150,unit:"g"},{name:"豆板醤",amount:1,unit:"大さじ"},{name:"甜麺醤",amount:1,unit:"大さじ"},{name:"醤油",amount:1,unit:"大さじ"},{name:"鶏がらスープ",amount:150,unit:"ml"},{name:"片栗粉",amount:2,unit:"大さじ"},{name:"ごま油",amount:1,unit:"小さじ"}],
    steps:["豆腐をさいの目切りに","ひき肉・豆板醤・甜麺醤を炒める","スープを加え豆腐を入れて煮る","水溶き片栗粉でとろみをつけて完成"]},
  { name:"餃子", emoji:"🥟", category:"中華", desc:"パリッと焼いてビールに最高", servings:4,
    ingredients:[{name:"豚ひき肉",amount:200,unit:"g"},{name:"キャベツ",amount:150,unit:"g"},{name:"ニラ",amount:0.5,unit:"束"},{name:"餃子の皮",amount:30,unit:"枚"},{name:"醤油",amount:1,unit:"大さじ"},{name:"ごま油",amount:1,unit:"大さじ"},{name:"にんにく",amount:1,unit:"かけ"},{name:"生姜",amount:1,unit:"かけ"}],
    steps:["キャベツを塩もみして水気を絞る","全材料を混ぜてよくこねる","皮で包む","フライパンで蒸し焼きにして完成"]},
  { name:"チャーハン", emoji:"🍳", category:"中華", desc:"パラパラ炒めて香ばしい", servings:2,
    ingredients:[{name:"ご飯",amount:400,unit:"g"},{name:"卵",amount:2,unit:"個"},{name:"ハム",amount:60,unit:"g"},{name:"ねぎ",amount:0.5,unit:"本"},{name:"醤油",amount:1,unit:"大さじ"},{name:"塩こしょう",amount:1,unit:"適量"},{name:"サラダ油",amount:2,unit:"大さじ"}],
    steps:["強火でフライパンを熱する","卵を炒めご飯を加えてほぐす","ハム・ねぎを加えて炒める","醤油を入れて味を整えて完成"]},
  { name:"エビチリ", emoji:"🦐", category:"中華", desc:"プリプリエビがたまらない", servings:2,
    ingredients:[{name:"えび",amount:200,unit:"g"},{name:"豆板醤",amount:1,unit:"小さじ"},{name:"ケチャップ",amount:2,unit:"大さじ"},{name:"鶏がらスープ",amount:100,unit:"ml"},{name:"にんにく",amount:1,unit:"かけ"},{name:"生姜",amount:1,unit:"かけ"},{name:"片栗粉",amount:1,unit:"大さじ"}],
    steps:["えびの背ワタを取り片栗粉をまぶす","えびを炒めて取り出す","にんにく・生姜・豆板醤・ケチャップを炒める","スープを加えとろみをつけえびを戻す"]},
  { name:"回鍋肉", emoji:"🥩", category:"中華", desc:"豆板醤が効いた本格中華", servings:2,
    ingredients:[{name:"豚バラ肉",amount:200,unit:"g"},{name:"キャベツ",amount:0.25,unit:"個"},{name:"ピーマン",amount:2,unit:"個"},{name:"豆板醤",amount:1,unit:"大さじ"},{name:"甜麺醤",amount:1,unit:"大さじ"}],
    steps:["豚バラを茹でてスライス","野菜を切る","豚肉を炒めて野菜を加える","豆板醤・甜麺醤で味付けして完成"]},
  { name:"酢豚", emoji:"🍍", category:"中華", desc:"甘酢あんがジューシー", servings:2,
    ingredients:[{name:"豚ロース",amount:250,unit:"g"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"ピーマン",amount:2,unit:"個"},{name:"にんじん",amount:0.5,unit:"本"},{name:"酢",amount:3,unit:"大さじ"},{name:"砂糖",amount:2,unit:"大さじ"},{name:"醤油",amount:2,unit:"大さじ"}],
    steps:["豚肉を揚げる","野菜を炒める","甘酢あんを作る","豚肉と野菜にあんをかけて完成"]},
  { name:"担々麺", emoji:"🍜", category:"中華", desc:"ゴマ香るピリ辛スープ", servings:2,
    ingredients:[{name:"中華麺",amount:2,unit:"玉"},{name:"豚ひき肉",amount:100,unit:"g"},{name:"豆板醤",amount:1,unit:"小さじ"},{name:"芝麻醤",amount:2,unit:"大さじ"},{name:"鶏がらスープ",amount:400,unit:"ml"},{name:"醤油",amount:1,unit:"大さじ"},{name:"ラー油",amount:1,unit:"適量"}],
    steps:["スープにねりごま・醤油・豆板醤を溶く","ひき肉を炒めてそぼろを作る","麺を茹でてスープを注ぐ","ひき肉・ねぎ・ラー油をのせて完成"]},
  { name:"青椒肉絲", emoji:"🫑", category:"中華", desc:"細切り肉とピーマンの炒め", servings:2,
    ingredients:[{name:"牛肉（薄切り）",amount:150,unit:"g"},{name:"ピーマン",amount:4,unit:"個"},{name:"たけのこ水煮",amount:100,unit:"g"},{name:"醤油",amount:1.5,unit:"大さじ"},{name:"オイスターソース",amount:1,unit:"大さじ"},{name:"ごま油",amount:1,unit:"小さじ"}],
    steps:["材料を細切りにする","牛肉に下味をつける","強火で牛肉を炒め取り出す","野菜を炒め牛肉を戻し調味料で味付け"]},
  { name:"麻婆なす", emoji:"🍆", category:"中華", desc:"とろとろなすに辛味噌", servings:2,
    ingredients:[{name:"なす",amount:3,unit:"本"},{name:"豚ひき肉",amount:100,unit:"g"},{name:"豆板醤",amount:1,unit:"大さじ"},{name:"甜麺醤",amount:1,unit:"大さじ"},{name:"鶏がらスープ",amount:100,unit:"ml"},{name:"片栗粉",amount:1,unit:"大さじ"}],
    steps:["なすを乱切りにして炒める","ひき肉・豆板醤・甜麺醤を炒める","スープを加えて煮る","とろみをつけてごま油で仕上げ"]},
  { name:"棒棒鶏", emoji:"🥒", category:"中華", desc:"ごまだれしっとり鶏", servings:2,
    ingredients:[{name:"鶏むね肉",amount:200,unit:"g"},{name:"きゅうり",amount:1,unit:"本"},{name:"ねりごま",amount:2,unit:"大さじ"},{name:"醤油",amount:1,unit:"大さじ"},{name:"酢",amount:1,unit:"大さじ"},{name:"砂糖",amount:1,unit:"小さじ"},{name:"ラー油",amount:1,unit:"適量"}],
    steps:["鶏むね肉を茹でてしっとり仕上げる","冷めたら手でほぐす","ごまだれを作る","きゅうりと鶏肉にたれをかけて完成"]},
  { name:"海老マヨ", emoji:"🦐", category:"中華", desc:"プリ海老にまろやかマヨソース", servings:2,
    ingredients:[{name:"えび",amount:200,unit:"g"},{name:"マヨネーズ",amount:3,unit:"大さじ"},{name:"ケチャップ",amount:1,unit:"大さじ"},{name:"レモン汁",amount:1,unit:"小さじ"},{name:"片栗粉",amount:2,unit:"大さじ"},{name:"揚げ油",amount:1,unit:"適量"}],
    steps:["えびの背ワタを取り片栗粉をまぶす","170℃でカリッと揚げる","ソースを作る","えびにソースを絡めて完成"]},
  { name:"チンジャオロース", emoji:"🫑", category:"中華", desc:"牛肉とピーマンの炒め物", servings:2,
    ingredients:[{name:"牛薄切り肉",amount:200,unit:"g"},{name:"ピーマン",amount:5,unit:"個"},{name:"オイスターソース",amount:1.5,unit:"大さじ"},{name:"醤油",amount:1,unit:"大さじ"},{name:"ごま油",amount:1,unit:"小さじ"}],
    steps:["牛肉・ピーマンを細切りに","牛肉に下味をつける","強火で牛肉を炒める","ピーマンを加え調味料で味付けして完成"]},
  { name:"春巻き", emoji:"🫔", category:"中華", desc:"パリパリ衣に具だくさん", servings:4,
    ingredients:[{name:"豚ひき肉",amount:100,unit:"g"},{name:"たけのこ水煮",amount:100,unit:"g"},{name:"春雨",amount:30,unit:"g"},{name:"春巻きの皮",amount:10,unit:"枚"},{name:"オイスターソース",amount:1,unit:"大さじ"},{name:"揚げ油",amount:1,unit:"適量"}],
    steps:["春雨を戻して炒め具を作る","皮で包む","170℃でキツネ色に揚げる","タレを添えていただく"]},
  { name:"八宝菜", emoji:"🦑", category:"中華", desc:"海鮮野菜あんかけ", servings:4,
    ingredients:[{name:"えび",amount:100,unit:"g"},{name:"いか",amount:100,unit:"g"},{name:"白菜",amount:0.25,unit:"個"},{name:"にんじん",amount:0.5,unit:"本"},{name:"鶏がらスープ",amount:200,unit:"ml"},{name:"オイスターソース",amount:2,unit:"大さじ"},{name:"片栗粉",amount:2,unit:"大さじ"}],
    steps:["具材を切る","えび・いかを炒めて取り出す","野菜を炒めスープを加える","海鮮を戻しとろみをつけて完成"]},
  // ===== アジア =====
  { name:"ガパオライス", emoji:"🌿", category:"アジア", desc:"バジル香るタイ定番飯", servings:2,
    ingredients:[{name:"鶏ひき肉",amount:200,unit:"g"},{name:"バジル",amount:20,unit:"g"},{name:"玉ねぎ",amount:0.5,unit:"個"},{name:"ピーマン",amount:2,unit:"個"},{name:"ナンプラー",amount:1.5,unit:"大さじ"},{name:"オイスターソース",amount:1,unit:"大さじ"},{name:"卵",amount:2,unit:"個"},{name:"ご飯",amount:2,unit:"膳"}],
    steps:["玉ねぎ・ピーマンを炒める","ひき肉を加えて炒める","ナンプラー・オイスターソースで味付け","バジルを入れご飯に盛り目玉焼きをのせる"]},
  { name:"グリーンカレー", emoji:"🥥", category:"アジア", desc:"ハーブ豊かなタイカレー", servings:4,
    ingredients:[{name:"鶏もも肉",amount:300,unit:"g"},{name:"ナス",amount:2,unit:"本"},{name:"グリーンカレーペースト",amount:3,unit:"大さじ"},{name:"ナンプラー",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"ココナッツミルク",amount:400,unit:"ml"}],
    steps:["ペーストをフライパンで炒める","鶏肉を加えて炒める","ナスを加えてナンプラーで調味","ココナッツミルクで煮て完成"]},
  { name:"ビビンバ", emoji:"🥚", category:"アジア", desc:"カラフル野菜ナムルのせ丼", servings:2,
    ingredients:[{name:"牛ひき肉",amount:150,unit:"g"},{name:"ほうれん草",amount:1,unit:"束"},{name:"にんじん",amount:1,unit:"本"},{name:"もやし",amount:1,unit:"袋"},{name:"卵",amount:2,unit:"個"},{name:"コチュジャン",amount:2,unit:"大さじ"},{name:"ごま油",amount:2,unit:"大さじ"},{name:"ご飯",amount:2,unit:"膳"}],
    steps:["各野菜をナムルにする","牛肉をコチュジャンで炒める","ご飯の上にナムルと肉を盛り付ける","温泉卵をのせてよく混ぜて食べる"]},
  { name:"プルコギ", emoji:"🥩", category:"アジア", desc:"甘辛タレで焼く韓国牛肉", servings:4,
    ingredients:[{name:"牛薄切り肉",amount:400,unit:"g"},{name:"玉ねぎ",amount:1,unit:"個"},{name:"にんじん",amount:0.5,unit:"本"},{name:"ねぎ",amount:1,unit:"本"},{name:"醤油",amount:3,unit:"大さじ"},{name:"砂糖",amount:1.5,unit:"大さじ"},{name:"ごま油",amount:1,unit:"大さじ"},{name:"おろしにんにく",amount:1,unit:"大さじ"}],
    steps:["牛肉をたれに30分以上漬ける","野菜を細切りにする","野菜を炒める","牛肉を加えて炒め合わせる"]},
  { name:"チャプチェ", emoji:"🥕", category:"アジア", desc:"春雨と野菜の韓国炒め", servings:2,
    ingredients:[{name:"韓国春雨",amount:100,unit:"g"},{name:"牛薄切り肉",amount:100,unit:"g"},{name:"ほうれん草",amount:0.5,unit:"束"},{name:"にんじん",amount:0.5,unit:"本"},{name:"醤油",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"ごま油",amount:1,unit:"大さじ"}],
    steps:["春雨を茹でて水切りする","牛肉・野菜を炒める","春雨を加えて醤油・砂糖で味付け","ごま油を回しかけて完成"]},
  { name:"パッタイ", emoji:"🍝", category:"アジア", desc:"ナンプラー香るタイ炒め麺", servings:2,
    ingredients:[{name:"米麺",amount:150,unit:"g"},{name:"えび",amount:8,unit:"尾"},{name:"卵",amount:2,unit:"個"},{name:"もやし",amount:1,unit:"袋"},{name:"ナンプラー",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"ライム",amount:1,unit:"個"}],
    steps:["米麺を水に30分浸けて戻す","えびを炒めて取り出す","麺を炒め卵を加えてほぐす","もやし・えびを加えナンプラーで味付け"]},
  { name:"ルーロー飯", emoji:"🍱", category:"アジア", desc:"台湾定番の煮込み豚丼", servings:4,
    ingredients:[{name:"豚バラ肉",amount:500,unit:"g"},{name:"にんにく",amount:3,unit:"かけ"},{name:"八角",amount:2,unit:"個"},{name:"醤油",amount:4,unit:"大さじ"},{name:"砂糖",amount:2,unit:"大さじ"},{name:"酒",amount:2,unit:"大さじ"},{name:"ゆで卵",amount:4,unit:"個"},{name:"ご飯",amount:4,unit:"膳"}],
    steps:["豚バラを2cm角に切る","にんにく・八角を炒めて香りを出す","豚肉・調味料・水を加えて煮立てる","弱火で1時間煮込んでご飯にかける"]},
  { name:"フォー", emoji:"🍜", category:"アジア", desc:"あっさりスープの米麺", servings:2,
    ingredients:[{name:"米麺",amount:160,unit:"g"},{name:"牛薄切り肉",amount:100,unit:"g"},{name:"もやし",amount:1,unit:"袋"},{name:"鶏がらスープ",amount:600,unit:"ml"},{name:"ナンプラー",amount:2,unit:"大さじ"},{name:"パクチー",amount:1,unit:"適量"},{name:"ライム",amount:1,unit:"個"}],
    steps:["米麺を水に浸けて戻す","スープをナンプラーで味付けする","麺を茹でて器に入れる","スープを注ぎ牛肉・パクチーをのせてライムを添える"]},
  { name:"サムギョプサル", emoji:"🥬", category:"アジア", desc:"豚バラをサンチュに巻いて", servings:4,
    ingredients:[{name:"豚バラ肉（厚切り）",amount:400,unit:"g"},{name:"サンチュ",amount:1,unit:"袋"},{name:"にんにく",amount:1,unit:"個"},{name:"コチュジャン",amount:2,unit:"大さじ"},{name:"ごま油",amount:1,unit:"大さじ"}],
    steps:["豚バラを食べやすく切る","フライパンやホットプレートで焼く","にんにくも焼く","サンチュにコチュジャンと共に巻いて食べる"]},
  { name:"チーズタッカルビ", emoji:"🧀", category:"アジア", desc:"とろけるチーズが絡む辛炒め", servings:2,
    ingredients:[{name:"鶏もも肉",amount:300,unit:"g"},{name:"コチュジャン",amount:2,unit:"大さじ"},{name:"コーン缶",amount:0.5,unit:"缶"},{name:"もち",amount:4,unit:"個"},{name:"ピザ用チーズ",amount:100,unit:"g"},{name:"醤油",amount:1,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"}],
    steps:["鶏肉をコチュジャン・醤油・砂糖に漬ける","フライパンで鶏肉・もちを炒める","コーンを加える","中央にチーズを乗せて溶けたら完成"]},
  { name:"トッポッキ", emoji:"🌶️", category:"アジア", desc:"モチモチ餅の甘辛炒め", servings:2,
    ingredients:[{name:"トッポッキ（棒餅）",amount:200,unit:"g"},{name:"ちくわ",amount:2,unit:"本"},{name:"コチュジャン",amount:2,unit:"大さじ"},{name:"砂糖",amount:1,unit:"大さじ"},{name:"醤油",amount:1,unit:"大さじ"},{name:"水",amount:200,unit:"ml"}],
    steps:["水・コチュジャン・砂糖・醤油でたれを作る","たれを煮立てる","餅とちくわを加えて煮る","餅が柔らかくなれば完成"]},
  { name:"ナシゴレン", emoji:"🍳", category:"アジア", desc:"インドネシアの焼き飯", servings:2,
    ingredients:[{name:"ご飯",amount:400,unit:"g"},{name:"えび",amount:8,unit:"尾"},{name:"卵",amount:2,unit:"個"},{name:"サンバルソース",amount:1,unit:"大さじ"},{name:"ナンプラー",amount:1,unit:"大さじ"},{name:"にんにく",amount:2,unit:"かけ"}],
    steps:["にんにくを炒めてえびを加える","ご飯を加えてほぐしながら炒める","サンバル・ナンプラーで味付け","目玉焼きをのせて完成"]},
  { name:"トムヤムクン", emoji:"🍲", category:"アジア", desc:"酸辛スープでエビぷりぷり", servings:2,
    ingredients:[{name:"えび",amount:8,unit:"尾"},{name:"マッシュルーム",amount:100,unit:"g"},{name:"トムヤムペースト",amount:2,unit:"大さじ"},{name:"ナンプラー",amount:2,unit:"大さじ"},{name:"ライム汁",amount:2,unit:"大さじ"},{name:"水",amount:500,unit:"ml"}],
    steps:["水にレモングラスを入れ煮出す","トムヤムペーストを溶かす","えびとマッシュルームを加える","ナンプラー・ライム汁で味を整えて完成"]},
];

// ============================================================
//  共通ユーティリティ
// ============================================================
window.Utils = {
  /** カテゴリカラー取得 */
  catColors: {
    和食:  { bg:"#fdf4e7", accent:"#c4733a", border:"#e8a050" },
    洋食:  { bg:"#edf7ed", accent:"#3a7a3a", border:"#60aa60" },
    中華:  { bg:"#fdeaea", accent:"#b03030", border:"#d06060" },
    アジア:{ bg:"#eaeff8", accent:"#3050a0", border:"#6070c0" },
  },

  /** 分量を人数比で整形 */
  formatAmount(amount, ratio) {
    const v = amount * ratio;
    if (v === Math.floor(v)) return String(Math.floor(v));
    return String(Math.round(v * 10) / 10);
  },

  /** ランダムに1件取得 */
  randomMeal() {
    return window.MEALS[Math.floor(Math.random() * window.MEALS.length)];
  },

  /** LINEシェア（アプリURL） */
  shareToLine(text) {
    const url = window.location.origin + window.location.pathname.replace(/\/[^/]*$/, '/index.html');
    const msg = text || `献立アプリ使ってみて！🍽️ ${window.MEALS.length}種類から今夜の夕食をランダム決定！`;
    window.open(
      `https://social-plugins.line.me/lineit/share?url=${encodeURIComponent(url)}&text=${encodeURIComponent(msg)}`,
      '_blank'
    );
  },

  /** ナビのアクティブクラスを現在のページに合わせる */
  setNavActive() {
    const current = location.pathname.split('/').pop() || 'index.html';
    document.querySelectorAll('.site-nav__link').forEach(a => {
      const href = a.getAttribute('href');
      if (href === current) a.classList.add('active');
    });
  },
};
